version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: plantonistas_prototipo_db
    environment:
      POSTGRES_USER: prototipo
      POSTGRES_PASSWORD: prototipo
      POSTGRES_DB: plantonistas_prototipo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
